databases:
  DB1:
    driver: mysql
    host: dev.mysql.com
    database: db1
    user: USER
    password: PASSWORD
  DB2:
    driver: sqlserver
    host: dev.sqlserver.com
    database: db2
    user: USER
    password: PASSWORD